### ISSUE TITLE
v0.4.4 release

### ISSUE THREAD

**Issue by japaric** [rtic-rs/cortex-m-rtic#244]
- [ ] make book point to the latest release
- [ ] ???

**Comment by korken89** [comment]
Agree on how to fix the MaybeUninit UB

**Comment by jonas-schievink** [comment]
Is the `mem::uninitialized` deprecation warning going to be fixed too? It's kind of difficult to work around right now.

**Comment by korken89** [comment]
It was now decided and a fix is being merged :)

**Comment by korken89** [comment]
See #289
