### ISSUE TITLE
Adding documentation to the app macro causes almost undebuggable error

### ISSUE THREAD

**Issue by korken89** [rtic-rs/cortex-m-rtic#288]
When adding a comment to the app macro as such:

```rust
/// Some text <- this causes the error
#[app(device = stm32f4xx_hal::stm32, peripherals = true)]
const APP: () = {
    #[init]
    fn init(cx: init::Context) {}
};
```

Gives the error:

```
error: expected `const`

error: aborting due to previous error
```

**Comment by japaric** [comment]
What is this supposed to do? Where is the doc comment supposed to be attached? I can certainly make the proc-macro ignore / drop the doc comment.

**Comment by korken89** [comment]
Issue cleanup: Please reopen if this is still active.
