### ISSUE TITLE
Publically exporting resource proxy types

### ISSUE THREAD

**Issue by MabezDev** [rtic-rs/cortex-m-rtic#291]
Following up from the discussion on matrix about the stability of the `resources` module generated by the app macro, what would be the implications of making the  app generated `resources` public?

Issue that provoked this question: https://gist.github.com/MabezDev/ecbf8546fc59a55ea404513be15868e3

Maxtrix discussion
```
japaric: so no, you can't avoid the generic type in a generic enum (or struct), but it's OK to use the resources::$ResourceName type

japaric: RTFM guarantees that it's a stable type name / path
```

cc: @japaric

**Comment by little-arhat** [comment]
@MabezDev could you please describe use cases? Or maybe provide publicly accessible link to matrix logs, if that was discussed there. Thanks!

**Comment by MabezDev** [comment]
@little-arhat Added some context.

**Comment by korken89** [comment]
Issue cleanup: Please reopen if this is still active.
