### ISSUE TITLE
Adding priority to scheduled task causes problem with resource methods not found

### ISSUE THREAD

**Issue by tstellanova** [rtic-rs/cortex-m-rtic#299]
Simply adding a `priority=2` to a scheduled task causes the rtfm expansion to produce code that will not build.  

I have a repeating scheduled task `imu_reader` that processes a series of incoming messages by calling a method `handle_all_messages`.  If I change the task defintion from:
```
 #[task(resources = [i2c1_driver], schedule = [imu_reader])]
```
to 

```
#[task(resources = [i2c1_driver], schedule = [imu_reader], priority = 2)]
```

I get the `cargo build` error:

```
error[E0599]: no method named `handle_all_messages` found for type `resources::i2c1_driver<'_>` in the current scope
   --> src/main.rs:140:34
    |
39  | #[app(device = stm32h7xx_hal::pac,  peripherals = true, monotonic = rtfm::cyccnt::CYCCNT)]
    | ------------------------------------------------------------------------------------------ method `handle_all_messages` not found for this
...
140 |         cx.resources.i2c1_driver.handle_all_messages();
    |                                  ^^^^^^^^^^^^^^^^^^^ method not found in `resources::i2c1_driver<'_>`
```

I may have misunderstood how to configure the rtfm task, but this is unexpected behavior. 
I've attached the original main.rs file as well as the good and bad expansions. 

[rtfm-priority-problem.zip](https://github.com/rtfm-rs/cortex-m-rtfm/files/4149275/rtfm-priority-problem.zip)

**Comment by perlindgren** [comment]
Hi
Could it be that its no longer an owned resource, so that you need to lock it before using it. The assymmetric API has both pro:s and con:s. Pro is that it makes it easy to use when you get an owned resource, cons is that an unrelated change to priority breaks the code. (There is an rfc/issue for making the API fully symmetric.)

**Comment by tstellanova** [comment]
I admit I don't fully understand the relationship between this simple test app and "the asymmetric API".  For what it's worth, this particular MCU only has one core. In this instance I simply added a priority to an existing task (and did not previously have any priority labels anywhere in the code).  I tried experimenting with locking according to the best available documentation, but with no progress. I subsequently removed the priority label.

**Comment by perlindgren** [comment]
The way you access a resource is asymmetric, depending wether there is any task with a higher priority accessing the same resource or not. See the example:

https://github.com/rtfm-rs/cortex-m-rtfm/blob/master/examples/lock.rs

and the book:

/rtfm.rs/0.5/book/en/by-example/resources.html

**Comment by PTaylor-FluenTech** [comment]
This threw me at first as well. It also makes things more difficult (for me as a new Rustacean) when passing access of the resource to other functions. Particularly, if I want to pass a Mutex so the lock can be made for a shorter duration only when needed within the other function.

Would it make sense to provide the resource wrapped in an Exclusive when a Mutex is not required? I think that would make the interfaces symmetric.
