### ISSUE TITLE
Merging SysTick and Monotonic clocks?

### ISSUE THREAD

**Issue by PTaylor-us** [rtic-rs/cortex-m-rtic#332]
Currently, the SysTick timer is used to wake the device when the next scheduled task is due (or SysTick overflows). I understand the desire to make RTIC only reliant on cortex-m resources. I believe it used to be the case that a custom _monotonic_ clock could not be used, but rather the CYCCNT was used exclusively. The _monotonic_ clock was abstracted, so perhaps the _scheduling timer_ (currently SysTick) could also be abstracted.

Another facet of this is that many device peripheral timers/rtcs have a compare register that can generate an interrupt. My current thought is that this would allow one timer to be used both for monotonic and scheduling timer functions.

One possible drawback to this idea is that it may be difficult to continue supporting SysTick as a possible scheduling timer due to its very different functionality.

#331 #312

**Comment by PTaylor-FluenTech** [comment]
I believe by adding a `feature` for conditional compilation, the default configuration could be to use the SysTick timer while, when enabled, the clock defined by the `monotonic` parameter could be used also as the scheduling timer. This would allow an implementation to achieve lower power operation by using, for example, an on-chip RTC  as both the monotonic clock and scheduling timer through use of compare interrupts.

**Comment by korken89** [comment]
The issue is that one needs a free running timer and a timer with match functionality to get RTICs internals for schedule to work. Usually this means using 2 timers, or at least 2 timer channels.

Was this what you had in mind?

**Comment by PTaylor-us** [comment]
You could use one free-running timer with at least one compare interrupt channel (is this what you meant by "match functionality"?). The wakeup is scheduled by loading the compare register with the result of a `wrapping_add` of the current timer count and the duration until the next task. Unfortunately, neither SysTick nor CYCCNT fit the bill, so you currently use them both. It would be nice if there was an _option_ to use one peripheral timer (such as an RTC or general-purpose timer) to handle the scheduling. This could allow very-low-power implementations.

**Comment by korken89** [comment]
Indeed, this is a good point.

I have added this as a point on the agenda to look into.

**Comment by Dirbaio** [comment]
In nRF52 chips the CYCCNT is not low-power because it requires HFCLK to be active. To do low-power you need to use an RTC, which uses LFCLK so it is low-power when the CPU is sleeping.
