### ISSUE TITLE
"app" attribute link broken in by-example/app.md

### ISSUE THREAD

**Issue by PTaylor-us** [rtic-rs/cortex-m-rtic#335]
I currently links to "https://github.com/rtic-rs/cortex-m-rtic/blob/master/book/api/cortex_m_rtic_macros/attr.app.html"

**Comment by AfoHT** [comment]
From here https://rtic.rs/0.5/book/en/by-example/app.html it correctly points to the following https://rtic.rs/0.5/api/cortex_m_rtic_macros/attr.app.html documentation page.

It is a relative link to the current URL requiring the API-docs which are built during publish/deploy to the gh-pages branch. If you had something else in mind just reopen this and we can investigate :+1:
