### ISSUE TITLE
Entry point and rust-analyzer

### ISSUE THREAD

**Issue by bugadani** [rtic-rs/cortex-m-rtic#354]
Right now, RTIC does not integrate well with rust-analyzer's entry point detection, which in turn means, that the handy "Run >" button is missing in VS Code for projects that use RTIC.

It would be really nice if this could be somehow resolved.

**Comment by korken89** [comment]
Hi, could you provide more information on what rust-analyzer is expecting or documentation of this feature?
After proc-macro expansion we are using the same as `cortex-m-rt` with our own `main` function, so I'm wonder what more is required.

**Comment by bugadani** [comment]
Maybe I should've checked before opening this issue, this is already known: https://github.com/rust-analyzer/rust-analyzer/issues/4771
