### ISSUE TITLE
No one code works with build on release 

### ISSUE THREAD

**Issue by no111u3** [rtic-rs/cortex-m-rtic#357]
I have some examples for `cortex-m-rtic` but no one works if I build its with `--release` flag. Simply reproduce code: https://github.com/no111u3/f401nucleo_robo_rust/blob/master/examples/rtic_blinky.rs (Its fully analog of one example in RTIC book on Timer Queue page).

**Comment by korken89** [comment]
Ah yes, all examples are falling into the LLVM `loop {}` optimization bug.
I'll make a fix for it.

Thanks for reporting!

**Comment by no111u3** [comment]
> Ah yes, all examples are falling into the LLVM `loop {}` optimization bug.
> I'll make a fix for it.
> 
> Thanks for reporting!

Thanks for fix, I applied it to my code and it works correctly.
