### ISSUE TITLE
cortex-m 0.6.3

### ISSUE THREAD

**Issue by Darneas** [rtic-rs/cortex-m-rtic#363]
Dear all,

would it be possible to push the dependency on cortex-m to 0.6.3? I want to use [knurling-rs/defmt](https://github.com/knurling-rs/defmt), which depends on 0.6.3. 

Or should I rather ask them to lower their dependency (e.g. ^0.6.0).

Best regards
Andreas

**Comment by korken89** [comment]
Hi,

You can provide your own version in your crate and RTIC will use the newer version.
This should solve you issue, could you try it out?

**Comment by Darneas** [comment]
Wow, didn't know that you can do that. It helped!

Thanks a lot 👍🏽

**Comment by korken89** [comment]
Glad it worked!
