### ISSUE TITLE
New `Monotonic` tracking issue

### ISSUE THREAD

**Issue by korken89** [rtic-rs/cortex-m-rtic#431]
Active development in:

* https://github.com/rtic-rs/rtic-core/tree/new_monotonic
* https://github.com/rtic-rs/rtic-syntax/tree/new_monotonic
* https://github.com/rtic-rs/cortex-m-rtic/tree/new_monotonic

**Comment by korken89** [comment]
The codegen seems to work now, tests, examples, docs needs updating now.
And we need to implement a Monotonic for DWT/SysTick combo.

**Comment by korken89** [comment]
Released!

**Comment by little-arhat** [comment]
@korken89 hello! is there rfc/motivation/rationale/docs and migration guide for this new monotonics? Thanks.

**Comment by mattico** [comment]
@little-arhat see https://hackmd.io/vWa9GvssR8qBfUYgMZm0CQ and https://github.com/rtic-rs/cortex-m-rtic/pull/312
