### ISSUE TITLE
[Book] Add chapter for hardware tasks/interrupts

### ISSUE THREAD

**Issue by jhillyerd** [rtic-rs/cortex-m-rtic#440]
The RTIC book would benefit from having an Interrupts/Hardware tasks chapter. As it stands, they aren't introduced formally, so the reader is left scrolling around the Resources and Software tasks chapters to learn about them.

Suggested topics:

- How to define a hardware task
- ` check_interrupt()`, `clear_interrupt_pending_bit()`, `clear_update_interrupt_flag()` still relevant or required in RTIC.

Points to make:

- A task fn can only be bound to single interrupt
- Bound interrupts must be removed from the app(dispatchers) list
- If you are defining a high priority task, you may want to leverage messaging queuing to do larger chunks of work in a lower priority software task

**Comment by perlindgren** [comment]
Thanks for the input.

Indeed the text could address the topics/points you mentioned (the info is partially there already, but can be made more explicit and easier to find).

There are also some examples of real applications in the `examples` repository, I think that many users are not aware of them.

**Comment by GregWoods** [comment]
>Bound interrupts must be removed from the app(dispatchers) list

Erm.. what? I'd love some elaboration on that. I can't recall reading it anywhere

**Comment by korken89** [comment]
@GregWoods The proc-macro will give an error if you have both, as you cannot have an interrupt bound as a hardware task and a dispatcher at the same time.

**Comment by GregWoods** [comment]
oops, sorry I deleted my comment after I received additional info from the matrix chat. Good to know you cannot assign to both.
