### ISSUE TITLE
[Book] Examples for lock_free and task_local

### ISSUE THREAD

**Issue by jhillyerd** [rtic-rs/cortex-m-rtic#446]
`#[lock_free]` and `#[task_local]` need examples to clarify their usage https://rtic.rs/dev/book/en/by-example/resources.html#lock-free-resource-access-of-mutable-resources

**Comment by japaric** [comment]
after PRs #498 & #500 `lock_free` is covered in the book and the migration guide. An example is included in this repo's `examples` directory and it's covered in the book.
`#[task_local]` was removed before alpha.3 but `task.locals` are covered in the resources section of the book. Closing this issue as done.
