### ISSUE TITLE
Cleanup of stale branches

### ISSUE THREAD

**Issue by AfoHT** [rtic-rs/cortex-m-rtic#457]
# Branch cleanup

We have a bunch of stale branches, in an effort to reduce repo size I'd like get some spring cleaning going.

Please take a look at your branches.

Branch owner/author:

### 4 years old

[mock branch, 3 commits](https://github.com/rtic-rs/cortex-m-rtic/tree/mock)

[next_claim, 2 commits](https://github.com/rtic-rs/cortex-m-rtic/commits/next_claim)

[next_claim_failed, 4 commits](https://github.com/rtic-rs/cortex-m-rtic/commits/next_claim_failed)

### 2 years old

[generators, 4 commits](https://github.com/rtic-rs/cortex-m-rtic/tree/generators)

[lockopt, 8 commits](https://github.com/rtic-rs/cortex-m-rtic/tree/lockopt)

### 1 year old

[memory_lane_experiment, 2 commits](https://github.com/rtic-rs/cortex-m-rtic/tree/memory_lane_experiment)

[task_local_experiment, merged to master in another form](https://github.com/rtic-rs/cortex-m-rtic/tree/task_local_experiment)

[ordering, 1 commit](https://github.com/rtic-rs/cortex-m-rtic/tree/ordering)

[immutable_resource_proxies, 7 commits](https://github.com/rtic-rs/cortex-m-rtic/tree/immutable_resource_proxies)

[systick, 4 commits, Systick and QEMU experiment](https://github.com/rtic-rs/cortex-m-rtic/tree/systick)

[vscode, 2 commits, Should maybe be part of examples instead?, nice to have](https://github.com/rtic-rs/cortex-m-rtic/tree/vscode)

### 4 years old

[checked, 1 commit](https://github.com/rtic-rs/cortex-m-rtic/tree/checked)

[read, 1 commit](https://github.com/rtic-rs/cortex-m-rtic/tree/read)

[claim, 1 commit](https://github.com/rtic-rs/cortex-m-rtic/tree/claim)

[no-threshold, 1 commit](https://github.com/rtic-rs/cortex-m-rtic/tree/no-threshold)

### 3 years old

[rooting, 1 commit closed with another solution merged](https://github.com/rtic-rs/cortex-m-rtic/tree/root)

[gh53, 1 commit workaround for M7 Basepri](https://github.com/rtic-rs/cortex-m-rtic/tree/gh53)

[tq, 24 commits building a WIP timer queue](https://github.com/rtic-rs/cortex-m-rtic/tree/tq)

### 2 years old

[message, 1 commit ahead, WIP avoid copying message payloads](https://github.com/rtic-rs/cortex-m-rtic/tree/message)

[gh184, 1 commit unlocking DWT when using TQ](https://github.com/rtic-rs/cortex-m-rtic/tree/gh184)

[v0.4.x-gh182, 8 commits related to issue #182](https://github.com/rtic-rs/cortex-m-rtic/tree/v0.4.x-gh182)

[thats-not-a-nail, 1 commit](https://github.com/rtic-rs/cortex-m-rtic/tree/thats-not-a-nail)

[generator-tasks, 1 commit, WIP generator tasks](https://github.com/rtic-rs/cortex-m-rtic/tree/generator-tasks)

### 2 years ago

[cortex-m-fix, 1 commit fixing Cargo for cortex-m 0.6](https://github.com/rtic-rs/cortex-m-rtic/tree/cortex-m-fix)

### 1 year old

[mutex-trait, 1 commit](https://github.com/rtic-rs/cortex-m-rtic/tree/mutex_trait)

### 3 years old 

[auto, no commit](https://github.com/rtic-rs/cortex-m-rtic/tree/auto)

### 2 years old

[trying, 1 commit, Seems like testing Bors](https://github.com/rtic-rs/cortex-m-rtic/tree/trying)

[translation, no commit](https://github.com/rtic-rs/cortex-m-rtic/tree/translation)

**Comment by japaric** [comment]
thanks for the heads up. I deleted mine. they were based on RTIC v0.2 I think (and looked a bit unsound ...)
