### ISSUE TITLE
[Book] Add 0.6 migration note about `Monotonic` priority

### ISSUE THREAD

**Issue by MabezDev** [rtic-rs/cortex-m-rtic#461]
I think it's worth noting that the default timer queue priority is now `1`, unless specified. I have a feeling many people will run into https://github.com/rtic-rs/cortex-m-rtic/issues/458 without this information.

Perhaps an example setting the `Monotonic` priority would be a good idea too.

**Comment by korken89** [comment]
Hi, thanks for the feedback!
I fully agree, I'm also not sure that following the same default of tasks makes sense for the monotonic. 
Or just not fixing the priority a default making users aware of the choice?

**Comment by MabezDev** [comment]
Perhaps a "sane" default with the ability to customize? I'm not sure how the prio of 6 was assigned to SysTick in 0.5.x in my project,  but that same logic could be used to generate a reasonable default priority.

**Comment by korken89** [comment]
Unfortunately the logic from 0.5 does on work in 0.6.
In 0.5 we took the maximum priority of all schedulable tasks, which were given by the `scheudle` parameter in the macro.
In spawn/schedule form anywhere this information is no longer available.

**Comment by korken89** [comment]
This is with #528  and #529 close to the old behavior of 0.5
