### ISSUE TITLE
Attributes for hardware tasks

### ISSUE THREAD

**Issue by jordens** [rtic-rs/cortex-m-rtic#462]
I would like to place a hardware task in ITCM. With RTIC 0.5 it mostly works fine if I place my task with `#[link_section = ...]`. However, this generates one wrapper function (the actual ISR) from RTIC that is not in ITCM and another `LongThunk` that is also not in ITCM. If I could assign attributes to the RTIC ISR (below for my reference) calling my hardware task, I'd expect both stubs/wrappers to disappear through inlining.

https://github.com/rtic-rs/cortex-m-rtic/blob/3c86d713a6f8fdb052de80380a17468090e42624/macros/src/codegen/hardware_tasks.rs#L43-L56)

**Comment by perlindgren** [comment]
Hi jordens.
Thanks for the input!

I think this part has been a bit slept on, and proper tests is lacking in RTIC 0.5. This is something that is on the "TODO" list for RTIC 0.6. 
/Per

**Comment by jordens** [comment]
Looks like this works now. Thanks!
