### ISSUE TITLE
Silent error when spawning a software task if rt feature is not enabled in device crate

### ISSUE THREAD

**Issue by etiandre** [rtic-rs/cortex-m-rtic#482]
### Affected version
0.5.6
### Bug description
If the "rt" feature is not enabled in the device crate, tasks won't spawn and will hang app execution, without any error or panics. 

### Reproduction steps
Using an STM32F303RE chip on a nucleo-F303 board, clone [this repo](https://github.com/etiandre/rtic-issue-sw-tasks)
run `cargo embed rtt`
see that only the "init" and "init end" messages are printed, but not "foo()" and "Spin"

**Comment by korken89** [comment]
This is fixed in `0.5.7`
