### ISSUE TITLE
link prominently to the examples repo

### ISSUE THREAD

**Issue by japaric** [rtic-rs/cortex-m-rtic#503]
this repo: https://github.com/rtic-rs/rtic-examples

at the start of this section here, probably: https://rtic.rs/dev/book/en/by-example/tips.html

question here: is the examples repo using 0.6? if yes, do we want to create a branch there that has examples for 0.5 and link to that from the 0.5 version of the rtic book?

**Comment by AfoHT** [comment]
Sounds good, excellent first issue as well!

Regarding the question: Examples repo separates different RTIC-versions by folders in the repo, so concurrently both 0.5 and 0.6 and future versions could be in there
