### ISSUE TITLE
[refactor] repetitive `mark_internal_ident` API calls

### ISSUE THREAD

**Issue by japaric** [rtic-rs/cortex-m-rtic#512]
there are several instances in the macros/codegen module where this pattern is used:
https://github.com/rtic-rs/cortex-m-rtic/blob/74b396497861ad69dcab0414851ddb8b5c624036/macros/src/codegen/software_tasks.rs#L39-L40

The first call creates a `task_name_fq` identifier; the second call prepends `internal_rtic` to it.

(AFAICT) the `task_name_fq` identifier is never used in the generated code so we could save the extra call by moving the `mark_internal_ident` function call into the `fq_ident` function.

That way one cannot 'forget' to call `mark_internal_ident` because `fq_ident` already returns an "internal" ident.
I think this also applies to the `inputs_ident` API.
I have checked the rest of the `util` API in detail but there may be more candidates for this simplification.

**Comment by korken89** [comment]
Indeed, this is used currently for all generated idents I think (as I did the copy/paste job).
It would be good to just add the "mark internal" in utils directly instead.
