### ISSUE TITLE
milliseconds with monotonic trait?

### ISSUE THREAD

**Issue by pdgilbert** [rtic-rs/cortex-m-rtic#559]
Since the commit `New monotonic trait working` I have been having trouble figuring out how to do a 500 millisecond duration.  I figured out `.seconds()` to `.secs()` but milliseconds still has me stumped. Suggestions would be appreciated.

Also would appreciate a pointer to where/how `. secs()` gets defined since I thought I  might find a clue about milliseconds there, but cannot even figure out how `.secs()` get implemented.

**Comment by jamwaffles** [comment]
I think you mean the `secs()` method in [`ExtU32`](https://docs.rs/fugit/latest/fugit/trait.ExtU32.html#tymethod.secs)? That also provides `millis`.

**Comment by pdgilbert** [comment]
Thanks @jamwaffles, `millis` was what I needed. And also thanks for the pointer to  [fugit's `ExtU32`](https://docs.rs/fugit/latest/fugit/trait.ExtU32.html#tymethod.secs) for `micros`, `minutes`, `hours`. My `blink_rtic` example is now building again,  CI at https://github.com/pdgilbert/rust-integration-testing/actions/

I'll close this issue, but I am still trying to understand `NOM` and `DENOM` which I seem to need when passing a `Duration` as an argument to a function. I think `NOM` would typically be 1 and `DENOM` would be the clock frequency, but I don't see why they would ever be different from that. A simple explanation or pointer to one would also be appreciated.

**Comment by burrbull** [comment]
> I'll close this issue, but I am still trying to understand `NOM` and `DENOM` which I seem to need when passing a `Duration` as an argument to a function. I think `NOM` would typically be 1 and `DENOM` would be the clock frequency, but I don't see why they would ever be different from that. A simple explanation or pointer to one would also be appreciated.

Just use TimerDuration alias for this

**Comment by pdgilbert** [comment]
Thanks @burrbull the TimerDuration  does make it simpler.
