### ISSUE TITLE
Dispatcher documentation

### ISSUE THREAD

**Issue by ostenning** [rtic-rs/cortex-m-rtic#576]
As a newcomer to this framework, I'm trying to get software tasks to work within my application running on the `stm32h7xx_hal` and I don't fully understand whats going on with Dispatchers and their dependency on the hardware, specifically I find this line [in the book](https://rtic.rs/1.0/book/en/by-example/software_tasks.html) is a little misleading `Software tasks are tasks which are not directly assigned to a specific interrupt vector`. At first I interpreted this as if a Dispatcher does not use any kind of hardware based interrupt at all, but then the documentation goes on to say that you need to assign a "free" interrupt vector to act as a dispatcher.

`stm32h7xx_hal` has no `SSI0` or `QEI0` symbols available, can _any_ unused interrupt vector be used? E.g. If my app is not using `EXTI0`, then this could be used? Are there any interrupts that generally shouldn't be used?

I think the documentation around this could be improved to help people

**Comment by korken89** [comment]
Hi,

Did you read the book on this subject?
https://rtic.rs/1.0/book/en/by-example/software_tasks.html

If so, what do you feel if missing?

**Comment by korken89** [comment]
Ah wait, you linked the same page.

> can any unused interrupt vector be used?

Yes.

> Are there any interrupts that generally shouldn't be used
 
No, all vector have settable priority so RTIC can use it as a dispatcher.

> specifically I find this line in the book is a little misleading.

This comes from that you as a user cannot select in which of the provided dispatchers the task will run, RTIC will select one. Software tasks are not directly linked to an interrupt as multiple software tasks are dispatched from a single hardware interrupt.
