### ISSUE TITLE
Released docs still indicate beta pre-release

### ISSUE THREAD

**Issue by x37v** [rtic-rs/cortex-m-rtic#596]
https://docs.rs/cortex-m-rtic/latest/rtic/

`HEADS UP This is an beta pre-release; there may be breaking changes in the API and semantics before a proper release is made.`

**Comment by AfoHT** [comment]
Thank you for reporting this!

It has already been fixed in latest upstream with [PR568](https://github.com/rtic-rs/cortex-m-rtic/pull/568) but we need to push a new release so docs.rs regenerates docs.
