### ISSUE TITLE
access device outside of init function

### ISSUE THREAD

**Issue by thepperson** [rtic-rs/cortex-m-rtic#625]
Is there a way to access the device field outside of the init function? If not, is there a way to pass those elements in a usable way to other functions?

**Comment by perlindgren** [comment]
You can pass peripherals using resources.

In many cases it is useful to not pass the peripheral as such, but rather some abstraction over a peripheral. In the case below an output pin (for controlling a led).

https://github.com/rtic-rs/rtic-examples/blob/master/rtic_v1/stm32f3_blinky/src/main.rs

/Per

**Comment by AfoHT** [comment]
If something still is unclear, feel free to reopen
