### ISSUE TITLE
RTIC introduces ambiguous assert!

### ISSUE THREAD

**Issue by evils** [rtic-rs/cortex-m-rtic#642]
i'm using `defmt::*` which imports `defmt::assert`

since my last `cargo update` (`cortex-m-rtic-macros v1.0.0 -> v1.1.2`)
a conflict with another `assert` macro was introduced
![image](https://user-images.githubusercontent.com/30512529/169728521-727acd33-d57f-44c9-b0ef-bdb5cb42f1bb.png)

switching to `use defmt::{trace, debug}` resolved this
(i was already using `defmt::assert!` explicitly, possibly for a similar problem)

the RTIC matrix channel suggested i look at `rtic-expansion.rs`
here is the snippet from there i believe to conflict with `defmt::assert` (via `defmt::*`)
```
{
    if rtic :: export :: is_armv6()
    {
        assert!
        ((stm32f4xx_hal :: pac :: Interrupt :: OTG_FS as u32) < 32)
        ;
    } else {}
} ;
```
@jamesmunns suggested that this problem could be avoided if RTIC namespaced its use of the assert macro

**Comment by jamesmunns** [comment]
It looks like this was introduced in https://github.com/rtic-rs/cortex-m-rtic/pull/589, in the `1.1.2` release.

**Comment by evils** [comment]
note that the changes on `master` since `1.1.2` also introduce a conflict with `defmt::panic`

**Comment by perlindgren** [comment]
Good catch, we will look into it.
/Per

**Comment by korken89** [comment]
@evils I checked the codegen and I could only find `assert!` that were colliding.
I was not able to find any `panic!` at all in the codegen. Where did you find the offending `panic!`?

**Comment by evils** [comment]
i also have no idea where the panic is
![image](https://user-images.githubusercontent.com/30512529/169947346-252defd3-ad46-427b-849d-46a5c20a9573.png)

do note i have basically this in my project, which does define a `fn panic`
https://github.com/knurling-rs/app-template/blob/main/src/lib.rs

(side note, screenshot is with your PR, it does resolve the assert conflict :) )

**Comment by korken89** [comment]
@evils Hmm, I built the template but can't find any panic.
Can you have a look in the `target/rtic-expansion.rs` file and print screen any panic?
This file holds the expanded RTIC code after codegen.

As long as we see it it context it should be easy to fix. :)

**Comment by korken89** [comment]
Wait what, your error says that it originates from inside `::core::assert`.

**Comment by evils** [comment]
oh, apparently `rg` ignores `target/`
but `rtic-expansion.rs` does not contain the string `panic`

**Comment by evils** [comment]
in case it's of use, my project is public
a `cargo update` at this point should yield the original error reported here
https://gitlab.com/evils/ASC/-/tree/5df5df8ba3846282f96dcd0ea713017c6b0969fe

and pointing `cortex-m-rtic` to the current master branch or your PR's branch,
should incur both or just the panic error, respectively

**Comment by korken89** [comment]
Hi, I gave it a try and can reproduce it.
The odd thing is that there is no `panic` in the code - it seems that the `assert!` macro expansion internally uses `panic!` instead of `::core::panic!` which causes the error.

I have switched in the codegen to not use `assert!` which solves the issue.
However this is a `core` lib bug...
